name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint "${{ github.workspace }}"
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --format @microsoft/eslint-formatter-sarif
            --output-file "${{ github.workspace }}/eslint-results.sarif"
        continue-on-error: true

      - name: Run ESLint with Score
        run: |
          # Install the formatter
          npm install eslint-formatter-score --save-dev
      
          # Run ESLint and extract the score
          SCORE=$(npx eslint . --ext .js,.ts --format score | grep -oP 'ESLint Score: \K\d+')
          echo "SCORE=$SCORE" >> $GITHUB_ENV

      - name: Debug - Verify SARIF file
        run: |
          ls -la
          if [ -f "eslint-results.sarif" ]; then
            echo "✅ SARIF file exists."
          else
            echo "❌ SARIF file NOT FOUND."
            exit 1  # Fail the workflow if missing
          fi

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "${{ github.workspace }}/eslint-results.sarif"
