name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint "${{ github.workspace }}"
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --format @microsoft/eslint-formatter-sarif
            --output-file "${{ github.workspace }}/eslint-results.sarif"
        continue-on-error: true

      - name: Calculate ESLint Score
        run: |
          # Extract errors/warnings from ESLint output (adapt regex as needed)
          ESLINT_OUTPUT=$(npx eslint . --config .eslintrc.js --ext .js,.ts --format json)
          ERRORS=$(echo "$ESLINT_OUTPUT" | jq '.[].errorCount' | awk '{sum+=$1} END {print sum}')
          WARNINGS=$(echo "$ESLINT_OUTPUT" | jq '.[].warningCount' | awk '{sum+=$1} END {print sum}')
      
          # Define weights and max issues
          ERROR_WEIGHT=2
          WARNING_WEIGHT=1
          TOTAL_FILES=$(find . -name "*.js" -o -name "*.ts" | wc -l)
          MAX_ISSUES=$((TOTAL_FILES * 2))  # Adjust multiplier as needed
      
          # Calculate score
          SCORE=$(awk -v e=$ERRORS -v w=$WARNINGS -v ew=$ERROR_WEIGHT -v ww=$WARNING_WEIGHT -v max=$MAX_ISSUES \
                    'BEGIN {print 100 - ((e*ew + w*ww) / max * 100)}')
      
          # Export score for future steps
          echo "ESLint Score: $SCORE%"
          echo "SCORE=$SCORE" >> $GITHUB_ENV

      - name: Debug - Verify SARIF file
        run: |
          ls -la
          if [ -f "eslint-results.sarif" ]; then
            echo "✅ SARIF file exists."
          else
            echo "❌ SARIF file NOT FOUND."
            exit 1  # Fail the workflow if missing
          fi

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "${{ github.workspace }}/eslint-results.sarif"
